---
- name: "Instala pacotes de dependencias do sistema operacional"
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - python
    - python-pip
    - python-backports.ssl-match-hostname
    - python3
    - python3-pip
    - curl
- name: Install requests library
  pip:
    name: requests
    state: present
  become: yes
